### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by ryan-williams** [ryan-williams/git-helpers#69]
h/t @arahuja

**Comment by arahuja** [comment]
`2to3` seems to do a decent job to update the script, but a dependency seems to be missing:
```
Traceback (most recent call last):
  File "/Users/arahuja/src/hammerlab/git-helpers/branch/git-branches", line 14, in <module>
    from util.branch_infos import BranchInfos
  File "/Users/arahuja/src/hammerlab/git-helpers/util/branch_infos.py", line 5, in <module>
    from .branch_info import BranchInfo
  File "/Users/arahuja/src/hammerlab/git-helpers/util/branch_info.py", line 5, in <module>
    from color import clen, color
ImportError: No module named 'color'
```

I can't find where `color` came from or what it is, any ideas?

**Comment by ryan-williams** [comment]
[color.py](https://github.com/ryan-williams/git-helpers/blob/cd6c3567aa9333ef0f890e5361b30ecdc9f6f0a3/util/color.py) actually lives in this repo.

I think I've got this ported, will PR it soon
