### ISSUE TITLE
"remove? [Y/n]" won't accept Y or y

### ISSUE THREAD

**Issue by danvk** [ryan-williams/git-helpers#78]
```
$ git add-mirror-remote demeter vanded03@hammerlab-dev3.hpc.mssm.edu:guacamole
Found existing remote: demeter; remove? [Y/n]: Y
Traceback (most recent call last):
  File "/Users/danvk/github/git-helpers/remote/git-add-mirror-remote", line 35, in <module>
    if not maybe_remove_remote_if_exists(remote_name):
  File "/Users/danvk/github/git-helpers/util/remotes.py", line 86, in maybe_remove_remote_if_exists
    if prompt('Found existing remote: %s; remove? [Y/n]: ' % remote_name):
  File "/Users/danvk/github/git-helpers/util/remotes.py", line 72, in prompt
    inp = input(p)
  File "<string>", line 1, in <module>
NameError: name 'Y' is not defined
```

**Comment by ryan-williams** [comment]
looks like a py3 `eval` incompatibility

**Comment by danvk** [comment]
I think you want `raw_input`, not `input`

**Comment by danvk** [comment]
I'll include a fix

**Comment by ryan-williams** [comment]
that's what I meant, thanks @danvk !
